[package]
name = "hithit_bot"
version = "0.1.0"
authors = ["PhotonQuantum <self@lightquantum.me>"]
edition = "2021"
license = "MIT"

[features]
default = ["webhook"]
webhook = ["teloxide-listener/webhook"]

[dependencies]
const_format = "0.2"
log = "0.4"
lru-cache = "0.1"
maplit = "1"
parking_lot = "0.11"
pest = "2.1.3"
pest_derive = "2.1.0"
pretty_env_logger = "0.4"
ranges = "0.3"
serde = "1"
serde_json = "1"
teloxide = { version = "0.5.3", features = ["auto-send"] }
thiserror = "1.0"
tokio = { version = "1.14", features = ["rt", "rt-multi-thread", "macros"] }
tokio-stream = "0.1"
teloxide-listener = { git = "https://github.com/PhotonQuantum/teloxide-listener" }
